version: "3.9"
services:
  customer-microservice-db:
    image: postgres:16.0
    container_name: customer-microservice-db-container
    environment:
      POSTGRES_DB: customer-microservice-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    restart: always
    volumes:
      - customer-microservice-db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  customer-microservice-db-volume: