spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5433/restaurant-microservice-db
    password: pass
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  mvc:
    format:
      date: iso
      time: iso
